server:
  environment: production
  debug: false
  #  host: 0.0.0.0
  port: 50001
  #  base_url: https://localhost:50001
  authentication:
    enforce: true
    require:
      token: true
    cookie:
      httpOnly: true
      secure: true
      sameSite: "lax"
      maxAge: 604800000 # 7*24*60*60*1000 = 604800000
      path: "/"
      domain: ".domain.com"
logging:
  level: 20 # 20 -> INFO
  #  levels: [10, 20, 30, 40, 50]
  use_telegram: false
#  directory: resources/logs
#  format: '%(asctime)s %(levelname)s %(message)s'
admin:
  username: "<admin username>"
  password: "<admin password>"
#database:
#  type: sqlite # sqlite, postgres
#  path:
#    relative: resources/databases/database.sqlite
##    absolute: null
telegram:
  enabled: false
  listen_commands: false
  token: "<token>"
  chat_id: "<chat id>"
  level: 20 # 20 -> INFO
  #  parse_mode: "HTML"
  admin:
    users: []
exchange:
  id: "cube"
exchanges:
  default: "cube"
  available:
    cube:
      environment: "production"
      api:
        key: "<exchange api key>"
        secret: "<exchange api secret>"
        password: "<exchange api password>"
      web_app:
        url: "https://dev.cube.exchange/"
      options:
        <option key>: "<option value>"
testing:
  integration:
    run: false
