server:
  environment: production
  debug: false
  #  host: 0.0.0.0
  port: 50001
  #  base_url: https://localhost:50001
  authentication:
    enforce: true
    require:
      token: true
logging:
  level: 20 # 20 -> INFO
  #  levels: [10, 20, 30, 40, 50]
  use_telegram: false
#  directory: resources/logs
#  format: '%(asctime)s %(levelname)s %(message)s'
telegram:
  enabled: false
  listen_commands: false
  token: "<token>"
  chat_id: "<chat id>"
  level: 20 # 20 -> INFO
  #  parse_mode: "HTML"
  admin:
    users: []
exchange:
  id: "cube"
  environment: "production"
  web_app:
    url: "https://cube.exchange/"
testing:
  integration:
    run: false
    credentials:
      exchange:
        api:
          key: "<exchange api key>"
          secret: "<exchange api secret>"
        options:
          subaccountId: "<exchange subaccountid option>"
