POST http://{{host}}:{{port}}/auth/signIn
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "exchangeEnvironment": "{{exchangeEnvironment}}",
  "userTelegramId": "{{userTelegramId}}",
  "exchangeApiKey": "{{exchangeApiKey}}",
  "exchangeApiSecret": "{{exchangeApiSecret}}",
  "exchangeOptions": {
    "subAccountId": "{{exchangeOptionsSubAccountId}}"
  }
}

###

POST http://{{host}}:{{port}}/auth/signOut
Authorization: Bearer {{token}}

###

POST http://{{host}}:{{port}}/auth/refresh
Authorization: Bearer {{token}}

###

POST http://{{host}}:{{port}}/auth/isSignedIn
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "userTelegramId": "{{userTelegramId}}"
}

###
