POST http://{{host}}:{{port}}/auth/signIn
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "exchangeEnvironment": "{{exchangeEnvironment}}",
  "exchangeApiKey": "{{exchangeApiKey}}",
  "exchangeApiSecret": "{{exchangeApiSecret}}",
  "exchangeOptions": {}
}

###

POST https://{{host}}:{{port}}/auth/signOut
Authorization: Bearer {{token}}

###

POST https://{{host}}:{{port}}/auth/refresh
Authorization: Bearer {{token}}

###

