GET http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_ticker",
  "parameters": {
    "symbol": "BTC/USDT"
  }
}

###

GET http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_markets",
  "parameters": null
}

###

