GET http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_markets",
  "parameters": {}
}

###

POST http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_ohlcv",
  "parameters": {
    "symbol": "tSOL/tUSDC"
  }
}

###

GET http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_ticker",
  "parameters": {
    "symbol": "tSOL/tUSDC"
  }
}

###

POST http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_balance",
  "parameters": {}
}

###

POST http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_open_orders",
  "parameters": {
  }
}

###

POST http://{{host}}:{{port}}/run/
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "exchangeId": "{{exchangeId}}",
  "environment": "{{exchangeEnvironment}}",
  "method": "fetch_order_book",
  "parameters": {
    "symbol": "BTC/USDC"
  }
}

###
